logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:file:./data/ecocert
    username: sa
    password:
    driver: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 87571465888-7j21dotsdv761cd35pmhifmb4vfqt5me.apps.googleusercontent.com
            clientSecret: QQG8fsgxTAmoSAFrFSaq5bbA
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 2087582348020127
            clientSecret: dff30d3cf4e6c31453464adc39b0b401
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  auth:
    tokenSecret: 926D96C80030DD58429D2751AC1BDBBC
    tokenExpirationMillis: 86400000
  oauth2:
    authorizedRedirectUris: http://localhost:3000/oauth2/redirect